# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 
import os

PWD = os.getcwd()
INPUT_PATH = "/mnt/shared/nationwide/cell_type_datasets"

rule all:
	input:
		f"{INPUT_PATH}/immune.rds"
	output:
		f"{PWD}/plots/umap_plot.png"
	container:
		"seurat/container:latest"
	shell:
		"docker run "
		"--user $(id -u):$(id -g) "
		f"-v {INPUT_PATH}/immune.rds:/data/immune.rds "
		f"-v {PWD}/scripts:/scripts "
		f"-v {PWD}/plots:/plots seurat/container:latest "
		"/scripts/r_scripts/sctransform_rpca.R" 